name: Flutter CI

on: push
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    # The flutter action needs java so include it
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # Include the flutter action
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'  
    # Get flutter packages
    - run: flutter pub get
      working-directory: Mads_Creator/
    # Build :D 
    - run: flutter test
      working-directory: Mads_Creator/
